// Auto-generated by proxy_gen.py
// 2025-12-08 20:42:20
#pragma once
#include <cstdint>

void SendCreateMyCharacter(int sessionIndex, uint32_t id, uint8_t dir, uint16_t x, uint16_t y, uint8_t hp) noexcept;
void SendCreateOtherCharacter(int sessionIndex, uint32_t id, uint8_t dir, uint16_t x, uint16_t y, uint8_t hp) noexcept;
void SendDeleteCharacter(int sessionIndex, uint32_t id) noexcept;
void SendMoveStart(int sessionIndex, uint32_t id, uint8_t dir, uint16_t x, uint16_t y) noexcept;
void SendMoveStop(int sessionIndex, uint32_t id, uint8_t dir, uint16_t x, uint16_t y) noexcept;
void SendAttack1(int sessionIndex, uint32_t id, uint8_t dir, uint16_t x, uint16_t y) noexcept;
void SendAttack2(int sessionIndex, uint32_t id, uint8_t dir, uint16_t x, uint16_t y) noexcept;
void SendAttack3(int sessionIndex, uint32_t id, uint8_t dir, uint16_t x, uint16_t y) noexcept;
void SendDamage(uint32_t attackerID, uint32_t targetID, uint8_t hp) noexcept;
void SendSync(int sessionIndex, uint32_t id, uint16_t x, uint16_t y) noexcept;