#!/usr/bin/env python3
"""Proxy Generator - Server to Client Packet Generation"""
import json
from datetime import datetime

TYPE_SIZES = {
    "uint8_t": 1,
    "uint16_t": 2,
    "uint32_t": 4,
}

def load_data(path='packets.json'):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def to_func_name(name):
    parts = name.replace('SC_', '').split('_')
    return 'Send' + ''.join(p.capitalize() for p in parts)

def generate_header(packets):
    lines = [
        f'// Auto-generated by proxy_gen.py',
        f'// {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
        '#pragma once',
        '#include <cstdint>',
        '',
    ]
    
    for pkt in packets:
        func = to_func_name(pkt['name'])
        send = pkt.get('send', 'Unicast')
        
        params = [] if send == 'Broadcast' else ['int sessionIndex']
        params.extend(f'{f["type"]} {f["name"]}' for f in pkt['fields'])
        
        lines.append(f'void {func}({", ".join(params)}) noexcept;')
    
    return '\n'.join(lines)

def generate_cpp(packets, header_code):
    lines = [
        f'// Auto-generated by proxy_gen.py',
        f'// {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
        '#include "stdafx.h"',
        '#include "Proxy.h"',
        '#include "Packet.h"',
        '#include "Protocol.h"',
        '#include "Express.h"',
        '',
    ]
    
    for pkt in packets:
        func = to_func_name(pkt['name'])
        fields = pkt['fields']
        send = pkt.get('send', 'Unicast')
        size = sum(TYPE_SIZES[f['type']] for f in fields)
        
        params = [] if send == 'Broadcast' else ['int sessionIndex']
        params.extend(f'{f["type"]} {f["name"]}' for f in fields)
        
        if send == 'Unicast':
            call = 'Express::GetInstance().Unicast(sessionIndex, &pkt);'
        elif send == 'Broadcast':
            call = 'Express::GetInstance().Broadcast(&pkt);'
        else:
            call = 'Express::GetInstance().BroadcastExcept(sessionIndex, &pkt);'
        
        lines.append(f'void {func}({", ".join(params)}) noexcept {{')
        lines.append('    Packet pkt;')
        lines.append(f'    pkt << (uint8_t){header_code} << (uint8_t){size} << (uint8_t)Type::{pkt["name"]};')
        
        for f in fields:
            lines.append(f'    pkt << {f["name"]};')
        
        lines.append(f'    {call}')
        lines.append('}')
        lines.append('')
    
    return '\n'.join(lines)

def main():
    data = load_data()
    packets = data.get('s2c', [])
    header_code = data.get('config', {}).get('header_code', '0x89')
    
    with open('Proxy.h', 'w', encoding='utf-8') as f:
        f.write(generate_header(packets))
    print('[OK] Proxy.h')
    
    with open('Proxy.cpp', 'w', encoding='utf-8') as f:
        f.write(generate_cpp(packets, header_code))
    print('[OK] Proxy.cpp')

if __name__ == '__main__':
    main()