// Auto-generated by stub_gen.py
// 2025-12-08 20:42:20
#include "stdafx.h"
#include "Stub.h"
#include "Packet.h"
#include "Protocol.h"
#include "Logic.h"

void ProcessPacket(int sessionIndex, Packet* packet) noexcept
{
    if (packet == nullptr) return;

    Type type = packet->GetType();
    packet->SkipHeader();

    uint8_t dir;
    uint16_t x;
    uint16_t y;

    switch (type) {
    case Type::CS_MOVE_START:
        *packet >> dir;
        *packet >> x;
        *packet >> y;
        Logic::GetInstance().OnMoveStart(sessionIndex, dir, x, y);
        break;
    case Type::CS_MOVE_STOP:
        *packet >> dir;
        *packet >> x;
        *packet >> y;
        Logic::GetInstance().OnMoveStop(sessionIndex, dir, x, y);
        break;
    case Type::CS_ATTACK1:
        *packet >> dir;
        *packet >> x;
        *packet >> y;
        Logic::GetInstance().OnAttack1(sessionIndex, dir, x, y);
        break;
    case Type::CS_ATTACK2:
        *packet >> dir;
        *packet >> x;
        *packet >> y;
        Logic::GetInstance().OnAttack2(sessionIndex, dir, x, y);
        break;
    case Type::CS_ATTACK3:
        *packet >> dir;
        *packet >> x;
        *packet >> y;
        Logic::GetInstance().OnAttack3(sessionIndex, dir, x, y);
        break;
    default:
        break;
    }
}