#!/usr/bin/env python3
"""Stub Generator - C2S Packet Handling Code Generator"""
import json
from datetime import datetime

def load_data(path='packets.json'):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def generate_stub(data):
    config = data.get('config', {})
    packets = data.get('c2s', [])
    
    handler_class = config.get('handler_class', 'Logic::GetInstance()')
    handler_prefix = config.get('handler_prefix', 'On')
    
    lines = [
        f'// Auto-generated by stub_gen.py',
        f'// {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
        '#include "stdafx.h"',
        '#include "Stub.h"',
        '#include "Packet.h"',
        '#include "Protocol.h"',
        '#include "Logic.h"',
        '',
        'void ProcessPacket(int sessionIndex, Packet* packet) noexcept',
        '{',
        '    if (packet == nullptr) return;',
        '',
        '    Type type = packet->GetType();',
        '    packet->SkipHeader();',
        '',
    ]
    
    # Variable Declaration 
    all_fields = {}
    for pkt in packets:
        for f in pkt['fields']:
            all_fields[f['name']] = f['type']
    
    for name, typ in sorted(all_fields.items()):
        lines.append(f'    {typ} {name};')
    
    lines.extend(['', '    switch (type) {'])
    
    for pkt in packets:
        lines.append(f'    case Type::{pkt["name"]}:')
        
        for f in pkt['fields']:
            lines.append(f'        *packet >> {f["name"]};')
        
        handler = handler_prefix + pkt.get('handler', pkt['name'].replace('CS_', ''))
        args = ', '.join(f['name'] for f in pkt['fields'])
        lines.append(f'        {handler_class}.{handler}(sessionIndex, {args});')
        lines.append('        break;')
    
    lines.extend([
        '    default:',
        '        break;',
        '    }',
        '}',
    ])
    
    return '\n'.join(lines)

def main():
    data = load_data()
    code = generate_stub(data)
    
    with open('Stub.cpp', 'w', encoding='utf-8') as f:
        f.write(code)
    
    print('[OK] Stub.cpp')

if __name__ == '__main__':
    main()
